// program to show try...catch in a program

const number= 150, value = 'abc';

try {
     console.log(number/abc);

    // forgot to define variable a      
    console.log(abc);
}
catch(error) {
    console.log('An error '); 
    console.log('Error message: ' + error);  
}
finally {
    console.log('Executed');
}
